version: "3"

services:
  ngram:
    build: .
    container_name: ngram
    env_file:
      - .env
    command:
      - sh
      - -c
      - |
        python main.py
    volumes:
      - ./avro:/avro
